### ISSUE TITLE
Connection loss after redeploy

### ISSUE THREAD

**Issue by admin-lm** [mschm/node-red-contrib-homekit#34] opened 2017-02-11 23:28 UTC
Hi, 

I created a home kit-device (temperature sensor), deploy it, add device on iPhone, everything works well.
After making changes in node-red, maybe my dashboard and deploy it again, iPhone losses connection to Home-Kit-Device and it's necessary to remove/search device &connect again.

**Comment by ljantos** [comment] 2017-02-18 17:40
I have the same problem. But after a complete node-red restart the iphone finds the devices again without a remove/search/connect... a little workaround for the moment.

**Comment by JonMurphy** [comment] 2017-02-24 18:30
Same issue for me as the OP.  A node-red restart does not help.  I need to remove the remove the device and then re-add the device to the iPhone.

**Comment by patnama** [comment] 2017-02-26 05:15
Same issue here.. :(

**Comment by lutwik** [comment] 2017-03-08 09:26
Same here. Removing the device and re-adding as @JonMurphy suggested works sometimes, but other times the accessory does not show up in HomeKit anymore and the only way to get it to show up is to re-name it (i.e. create a new one with another name).

**Comment by iOlli** [comment] 2017-03-11 14:04
Same here. 
But another issue. Only the WindowCovering (connected to KNX roller shutter) loose connection after one day and the accessory status in HomeKit on the iPhone is "Anwortet nicht (does not respond)".

**Comment by swissglider** [comment] 2017-03-25 13:21
I do have the same issue.
Have new installed whole rpi with everything the latest version.
I have the node-red-contrib-homekit 0.2.0 and node-red 0.16.2

Always if I need to deploy I need manuelly to stop node-red and than to start it again, that homekit can act again. If I do not restart, there is no longer a connection to the homekit device.

**Comment by maragelis** [comment] 2017-03-31 05:31
I have noticed this happening only on the sensor service and when using bridge service (-try not to use bridge service). I recommend checking the payloads you are sending to home bridge as a wrong payload can take the service offline. Second don't use full deploy but node change deploy in node. Third get the HomeKit.js from the #25 pull request. Forth on startup it helps to inject a payload into sensor service nodes just to have an initial value. All the above helped me and now am enjoying my smart home as intended.

**Comment by waj** [comment] 2017-06-22 12:32
Isn't this a duplicate of #20?

**Comment by mschm** [comment] 2017-07-08 19:23
As mentioned by @waj, I also consider this issue as duplicate of #20. Thanks for pointing it out.

**Comment by mschm** [comment] 2017-07-08 21:51
Hi everybody, please update to the newest version (0.2.1) and let me know, if it works for you now.

**Closed** 2017-07-09 13:13 UTC
Labels: duplicate

**Comment by lsafelix75** [comment] 2018-03-04 15:49
Not working with latest 1.1.3

**Comment by olapola85** [comment] 2018-03-06 05:47
+1

**Comment by oliverrahner** [comment] 2018-04-12 04:56
Same issue here...
