### ISSUE TITLE
"Error: dns service error: name conflict" on re-deploy

### ISSUE THREAD

**Issue by jclement** [mschm/node-red-contrib-homekit#5] opened 2016-11-11 13:54 UTC
This block is AWESOME!  

However, I'm running into issues when I re-deploy a flow with a Homekit node in it.  It's looking like it's not unregistering the device names with Avahi before trying to register them again. 

I took quick attempt at fixing it but only succeeding in upgrading it to a segmentation fault.  

To reproduce: create a flow with a single switch, logging to a debug block.  Deploy.  change something slightly.  Redeploy.  Service crashes with following error.

```
11 Nov 06:42:33 - Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/home/nodered/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:55:10)
    at Object.create [as createAdvertisement] (/home/nodered/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:63:10)
    at Advertiser.startAdvertising (/home/nodered/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Accessory._onListening (/home/nodered/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Accessory.js:526:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/home/nodered/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/HAPServer.js:185:8)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)
    at EventedHTTPServer.<anonymous> (/home/nodered/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1274:10)
    at nextTickCallbackWith1Arg (node.js:447:9)
    at process._tickCallback (node.js:369:17)
```

## Dependencies

```
11 Nov 06:52:32 - [info] Node-RED version: v0.15.2
11 Nov 06:52:32 - [info] Node.js  version: v4.6.2
11 Nov 06:52:32 - [info] Linux 4.4.0-31-generic x64 LE
```

```
ii  avahi-daemon                       0.6.32~rc+dfsg-1ubuntu2           amd64        Avahi mDNS/DNS-SD daemon
ii  libavahi-client-dev                0.6.32~rc+dfsg-1ubuntu2           amd64        Development files for the Avahi client library
ii  libavahi-client3:amd64             0.6.32~rc+dfsg-1ubuntu2           amd64        Avahi client library
ii  libavahi-common-data:amd64         0.6.32~rc+dfsg-1ubuntu2           amd64        Avahi common data files
ii  libavahi-common-dev                0.6.32~rc+dfsg-1ubuntu2           amd64        Development files for the Avahi common library
ii  libavahi-common3:amd64             0.6.32~rc+dfsg-1ubuntu2           amd64        Avahi common library
ii  libavahi-compat-libdnssd-dev       0.6.32~rc+dfsg-1ubuntu2           amd64        Development headers for the Avahi Apple Bonjour compatibility library
ii  libavahi-compat-libdnssd1:amd64    0.6.32~rc+dfsg-1ubuntu2           amd64        Avahi Apple Bonjour compatibility library
ii  libavahi-core7:amd64               0.6.32~rc+dfsg-1ubuntu2           amd64        Avahi's embeddable mDNS/DNS-SD library
```

```
└─┬ node-red-contrib-homekit@0.0.1
  └─┬ hap-nodejs@0.4.15
    ├── buffer-shims@1.0.0
    ├─┬ curve25519-n@1.1.0
    │ ├── bindings@1.2.1
    │ └── nan@2.4.0
    ├─┬ debug@2.3.2
    │ └── ms@0.7.2
    ├─┬ ed25519@0.0.4
    │ ├── bindings@1.2.1
    │ └── nan@2.4.0
    ├── fast-srp-hap@1.0.0
    ├── ip@1.1.4
    ├─┬ mdns@2.3.3
    │ ├── bindings@1.2.1
    │ └── nan@2.3.5
    └─┬ node-persist@0.0.8
      ├── mkdirp@0.3.5
      └── q@1.1.2

```

**Comment by jclement** [comment] 2016-11-11 15:59
I was able to resolve it with this.  I don't like that it's peeking into the Accessory and poking the _advertiser directly.

https://github.com/jclement/node-red-contrib-homekit/commit/8174287625482a5d6bf8707359db9e68b8f57b7d#diff-2e803fd70babf2297f53bff75c9c9cf2

**Comment by mschm** [comment] 2016-11-12 02:52
Thanks for the detailed report! (Un)fortunately I cannot reproduce the name conflict on my Mac. Will have another look at it on Ubuntu tomorrow. 
But I somehow remember that I had a similar issue before and that I was looking for a way to correctly unregister an accessory – didn't find it ;) Probably @KhaosT can tell what the best-practice is here...

**Comment by KhaosT** [comment] 2016-11-12 03:04
Ah, the design of accessory didn't account for situation like a program creates accessory, deallocate it and then recreate a similar one. I'll try to make some changes to hap-nodejs to handle situation like this.

**Comment by samgot1** [comment] 2016-12-22 17:56
I have the same error. First tried with Raspbian, now the same thing in Ubuntu 16.10

`22 Dec 18:50:31 - Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/home/chris/.node-red/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/home/chris/.node-red/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/home/chris/.node-red/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Accessory._onListening (/home/chris/.node-red/node_modules/hap-nodejs/lib/Accessory.js:539:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/home/chris/.node-red/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)
`
`22 Dec 18:49:17 - [info] Node-RED version: v0.15.2
22 Dec 18:49:17 - [info] Node.js  version: v4.2.6
22 Dec 18:49:17 - [info] Linux 4.8.0-30-generic x64 LE
`

**Comment by mschm** [comment] 2016-12-26 23:09
Should be fixed now. If not, feel free to reopen :)

**Closed by mschm** 2016-12-26 23:09 UTC
Labels: bug

**Comment by 007hacky007** [comment] 2017-12-21 19:25
One year later and I'm having this issue with latest versions. :(

`Dec 21 19:44:40 controller-1 Node-RED[18011]: 21 Dec 19:44:40 - [red] Uncaught Exception:
Dec 21 19:44:40 controller-1 Node-RED[18011]: 21 Dec 19:44:40 - Error: dns service error: name conflict
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at Error (native)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at new Advertisement (/home/nodered/.node-red/node_modules/mdns/lib/advertisement.js:56:10)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at Object.create [as createAdvertisement] (/home/nodered/.node-red/node_modules/mdns/lib/advertisement.js:64:10)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at Advertiser.startAdvertising (/home/nodered/.node-red/node_modules/hap-nodejs/lib/Advertiser.js:47:30)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at Accessory._onListening (/home/nodered/.node-red/node_modules/hap-nodejs/lib/Accessory.js:655:20)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at emitOne (events.js:96:13)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at HAPServer.emit (events.js:188:7)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at HAPServer._onListening (/home/nodered/.node-red/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at emitOne (events.js:96:13)
Dec 21 19:44:40 controller-1 Node-RED[18011]:     at EventedHTTPServer.emit (events.js:188:7)`

`├─┬ node-red-contrib-homekit@0.2.1
│ └─┬ hap-nodejs@0.4.36
│   ├── buffer-shims@1.0.0
│   ├── curve25519-n2@1.1.3
│   ├── decimal.js@7.5.1
│   ├── ed25519@0.0.4
│   ├── fast-srp-hap@1.0.1
│   ├── ip@1.1.5
│   ├─┬ mdns@2.3.4
│   │ └── nan@2.3.5
│   └─┬ node-persist@0.0.11
│     ├─┬ mkdirp@0.5.1
│     │ └── minimist@0.0.8
│     └── q@1.1.2`

Any advice? Unfortunately I don't code in JS, so I'm unable to write hotfix by myself. 
Thank you in advance!

**Comment by piejanssens** [comment] 2017-12-23 07:21
Restart node-red.

**Comment by 007hacky007** [comment] 2017-12-23 11:06
It restarts automatically after each crash. Tried also to reboot whole system. To circumvent this I have to deploy just changed nodes instead of all nodes or it crashes instantly. :(

**Comment by piejanssens** [comment] 2017-12-23 11:26
I also use the option to deploy the changed nodeso only.

**Comment by bland328** [comment] 2018-01-06 21:37
Same here, but would love a better solution. Happy to collect debugging info, if helpful.

**Comment by rikki78** [comment] 2018-01-18 13:43
Same issue here!
